import { ShieldAlert } from "lucide-react";

export function ResponsibleAiNotice() {
  return (
    <div className="glass mt-6 flex items-start gap-3 rounded-xl border border-primary/20 p-4 text-xs text-muted-foreground">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p>
        <span className="font-semibold text-foreground">Responsible AI:</span> Outputs are
        generated by an AI model and may be incomplete, inaccurate, or reflect biases. Always
        review and edit before sharing, sending, or acting on this content.
      </p>
    </div>
  );
}
